##Numpy:Package for Multidimensional array

#Numpy:Package for Dimensional array

In [2]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [24]:
np.random.rand(3,5)

array([[0.92011086, 0.9137617 , 0.05501747, 0.80254561, 0.04089428],
       [0.03980114, 0.52096406, 0.87120879, 0.62876939, 0.81325613],
       [0.09426394, 0.47601786, 0.10615044, 0.86999582, 0.46101725]])

In [27]:
arr=np.random.randn(2,4)
arr

array([[ 0.27945645,  0.57316093,  0.23204068,  1.1196079 ],
       [ 0.39963048,  0.0625611 ,  0.51075904, -0.25815538]])

In [32]:
np.random.randint(2,4)

2

In [30]:
np.random.randint(20,56,100)

array([25, 21, 54, 47, 30, 22, 23, 30, 38, 38, 22, 25, 47, 21, 31, 48, 42,
       27, 48, 20, 22, 26, 49, 33, 22, 39, 54, 31, 35, 43, 50, 41, 55, 51,
       30, 20, 26, 51, 39, 37, 32, 48, 21, 31, 45, 42, 22, 34, 33, 20, 27,
       35, 23, 25, 46, 34, 26, 30, 38, 30, 42, 23, 20, 31, 23, 33, 22, 45,
       52, 34, 49, 45, 41, 53, 33, 33, 32, 31, 49, 21, 53, 23, 47, 28, 47,
       23, 27, 23, 55, 30, 39, 32, 51, 29, 53, 26, 28, 52, 21, 36])

In [33]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
rand_array=np.random.randint(0,10,50)
rand_array

array([1, 7, 6, 9, 4, 5, 6, 3, 5, 7, 2, 3, 5, 0, 1, 4, 1, 6, 8, 1, 4, 7,
       1, 6, 1, 0, 1, 7, 9, 7, 8, 9, 2, 2, 1, 1, 9, 2, 9, 3, 9, 2, 7, 5,
       9, 5, 1, 7, 7, 0])

In [35]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])